---
title: "Change in Sea level"
description: |
  Examination of climate changes impact On sea level.
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

library(tidyverse)
library(ggthemes)
library(knitr)
library(rmarkdown)
library(gt)
library(gganimate)
library(gifski)
library(png)
library(ggpubr)
```

```{r data}
raw_data <- read_csv("csiro_alt_gmsl_mo_2015.csv", col_types = cols(
  Time = col_date(format = ""),
  GMSL = col_double()
)) %>%
  as_tibble()


```
```{r Sea-Level}
read_rds("Sea-Level-Animation.rds")
```

The increase in Sea level is relatively constant

```{r}
read_rds("Sea-Level-Still.rds")
```

The value of R is 0.99 which correlates with the line graphs data. However, that can be due to other factors such as land rising (look at "About" for more info). This gradual increase is mainly speculated to be due to climate change.

```{r table-4}
gt(raw_data, rownames_to_stub = TRUE) %>%
  tab_header(title = md("**Global Absolute Sea Level**"), subtitle = "Sea Level Increases As Time Progresses") %>%
  tab_source_note("Source: NOAA (2015)")
```
Link to Data Website: https://datahub.io/core/sea-level-rise#data

